package gateway

func (s *system) registerRoutes() {
	s.mux.HandleFunc("POST /api/runs", s.authWrap(s.handleStartRun))
	s.mux.HandleFunc("GET /api/runs/{runID}", s.authWrap(s.handleGetRun))
	s.mux.HandleFunc("POST /api/runs/{runID}/cancel", s.authWrap(s.handleCancelRun))
	s.mux.HandleFunc("POST /api/tool-confirmations", s.authWrap(s.handleToolConfirmation))

	s.mux.HandleFunc("GET /api/roles", s.authWrap(s.handleListRoles))
	s.mux.HandleFunc("POST /api/roles", s.authWrap(s.handleSaveRole))
	s.mux.HandleFunc("GET /api/roles/{roleID}", s.authWrap(s.handleLoadRole))
	s.mux.HandleFunc("DELETE /api/roles/{roleID}", s.authWrap(s.handleDeleteRole))
	s.mux.HandleFunc("GET /api/roles/{roleID}/avatar", s.authWrap(s.handleLoadRoleAvatar))
	s.mux.HandleFunc("PUT /api/roles/{roleID}/avatar", s.authWrap(s.handleSaveRoleAvatar))
	s.mux.HandleFunc("DELETE /api/roles/{roleID}/avatar", s.authWrap(s.handleDeleteRoleAvatar))

	s.mux.HandleFunc("GET /api/roles/{roleID}/sessions", s.authWrap(s.handleListSessions))
	s.mux.HandleFunc("POST /api/roles/{roleID}/sessions/create", s.authWrap(s.handleCreateSession))
	s.mux.HandleFunc("POST /api/roles/{roleID}/sessions", s.authWrap(s.handleSaveSession))
	s.mux.HandleFunc("GET /api/roles/{roleID}/sessions/{sessionID}", s.authWrap(s.handleLoadSession))
	s.mux.HandleFunc("DELETE /api/roles/{roleID}/sessions/{sessionID}", s.authWrap(s.handleDeleteSession))
	s.mux.HandleFunc("PATCH /api/roles/{roleID}/sessions/{sessionID}/title", s.authWrap(s.handleUpdateSessionTitle))
	s.mux.HandleFunc("PATCH /api/roles/{roleID}/sessions/{sessionID}/messages/{messageID}", s.authWrap(s.handleUpdateSessionMessage))
	s.mux.HandleFunc("DELETE /api/roles/{roleID}/sessions/{sessionID}/messages/{messageID}", s.authWrap(s.handleDeleteSessionMessage))
	s.mux.HandleFunc("DELETE /api/roles/{roleID}/sessions/{sessionID}/messages/{messageID}/subtree", s.authWrap(s.handleDeleteSessionMessageSubtree))
	s.mux.HandleFunc("GET /api/session-attachments/image", s.authWrap(s.handleLoadSessionAttachmentImage))

	s.mux.HandleFunc("GET /api/providers", s.authWrap(s.handleListProviders))
	s.mux.HandleFunc("POST /api/providers", s.authWrap(s.handleSaveProvider))
	s.mux.HandleFunc("GET /api/providers/{providerID}", s.authWrap(s.handleLoadProvider))
	s.mux.HandleFunc("DELETE /api/providers/{providerID}", s.authWrap(s.handleDeleteProvider))
	s.mux.HandleFunc("POST /api/providers/{providerID}/models/refresh", s.authWrap(s.handleRefreshProviderModels))

	s.mux.HandleFunc("GET /api/tools", s.authWrap(s.handleListTools))
	s.mux.HandleFunc("POST /api/tools", s.authWrap(s.handleSaveTool))
	s.mux.HandleFunc("GET /api/tools/{toolID}", s.authWrap(s.handleLoadTool))

	s.mux.HandleFunc("GET /api/stickers", s.authWrap(s.handleLoadStickerLibrary))
	s.mux.HandleFunc("GET /api/stickers/image", s.authWrap(s.handleLoadStickerImage))
	s.mux.HandleFunc("POST /api/stickers/categories", s.authWrap(s.handleCreateStickerCategory))
	s.mux.HandleFunc("GET /api/stickers/categories", s.authWrap(s.handleListStickerCategories))
	s.mux.HandleFunc("GET /api/stickers/categories/{categoryName}", s.authWrap(s.handleLoadStickerCategory))
	s.mux.HandleFunc("DELETE /api/stickers/categories/{categoryName}", s.authWrap(s.handleDeleteStickerCategory))
	s.mux.HandleFunc("POST /api/stickers/items", s.authWrap(s.handleAddSticker))
	s.mux.HandleFunc("PATCH /api/stickers/items/name", s.authWrap(s.handleRenameSticker))
	s.mux.HandleFunc("DELETE /api/stickers/items", s.authWrap(s.handleDeleteSticker))
	s.mux.HandleFunc("GET /api/assist/stickers/name/config", s.authWrap(s.handleLoadStickerNamingConfig))
	s.mux.HandleFunc("PUT /api/assist/stickers/name/config", s.authWrap(s.handleSaveStickerNamingConfig))
	s.mux.HandleFunc("POST /api/assist/stickers/name", s.authWrap(s.handleGenerateStickerName))
	s.mux.HandleFunc("GET /api/assist/mermaid-fix/config", s.authWrap(s.handleLoadMermaidFixConfig))
	s.mux.HandleFunc("PUT /api/assist/mermaid-fix/config", s.authWrap(s.handleSaveMermaidFixConfig))
	s.mux.HandleFunc("POST /api/assist/mermaid-fix", s.authWrap(s.handleFixMermaidInMessage))
	s.mux.HandleFunc("GET /api/assist/chat-title/config", s.authWrap(s.handleLoadChatTitleNamingConfig))
	s.mux.HandleFunc("PUT /api/assist/chat-title/config", s.authWrap(s.handleSaveChatTitleNamingConfig))
	s.mux.HandleFunc("POST /api/assist/chat-title", s.authWrap(s.handleGenerateChatTitle))

	s.mux.HandleFunc("GET /ws/events", s.handleEventsWebSocket)
}
