package gateway

func (s *system) registerRoutes() {
	if s.config.LocalRun {
		s.mux.HandleFunc("GET /api/local-run", s.localAuthWrap(s.handleLocalRun))
		s.mux.HandleFunc("POST /api/local-run/stop", s.localAuthWrap(s.handleLocalRunStop))
	}
	s.mux.HandleFunc("GET /api/release", s.authWrap(s.handleRelease))
	s.mux.HandleFunc("GET /api/release-checks", s.authWrap(s.handleReleaseChecks))
	s.mux.HandleFunc("POST /api/release-checks/refresh", s.authWrap(s.handleRefreshReleaseChecks))
	s.mux.HandleFunc("POST /api/runs", s.authWrap(s.handleStartRun))
	s.mux.HandleFunc("GET /api/runs", s.authWrap(s.handleListActiveRuns))
	s.mux.HandleFunc("GET /api/runs/{runID}", s.authWrap(s.handleGetRun))
	s.mux.HandleFunc("POST /api/runs/{runID}/cancel", s.authWrap(s.handleCancelRun))
	s.mux.HandleFunc("GET /api/async-tool-tasks", s.authWrap(s.handleListAsyncToolTasks))
	s.mux.HandleFunc("POST /api/tool-confirmations", s.authWrap(s.handleToolConfirmation))

	s.mux.HandleFunc("GET /api/roles", s.authWrap(s.handleListRoles))
	s.mux.HandleFunc("POST /api/roles", s.authWrap(s.handleSaveRole))
	s.mux.HandleFunc("GET /api/roles/{roleID}", s.authWrap(s.handleLoadRole))
	s.mux.HandleFunc("DELETE /api/roles/{roleID}", s.authWrap(s.handleDeleteRole))
	s.mux.HandleFunc("GET /api/roles/{roleID}/avatar", s.authWrap(s.handleLoadRoleAvatar))
	s.mux.HandleFunc("PUT /api/roles/{roleID}/avatar", s.authWrap(s.handleSaveRoleAvatar))
	s.mux.HandleFunc("DELETE /api/roles/{roleID}/avatar", s.authWrap(s.handleDeleteRoleAvatar))

	s.mux.HandleFunc("GET /api/groups", s.authWrap(s.handleListChatGroups))
	s.mux.HandleFunc("POST /api/groups", s.authWrap(s.handleSaveChatGroup))
	s.mux.HandleFunc("GET /api/groups/{groupID}", s.authWrap(s.handleLoadChatGroup))
	s.mux.HandleFunc("DELETE /api/groups/{groupID}", s.authWrap(s.handleDeleteChatGroup))
	s.mux.HandleFunc("GET /api/groups/{groupID}/avatar", s.authWrap(s.handleLoadChatGroupAvatar))
	s.mux.HandleFunc("PUT /api/groups/{groupID}/avatar", s.authWrap(s.handleSaveChatGroupAvatar))
	s.mux.HandleFunc("DELETE /api/groups/{groupID}/avatar", s.authWrap(s.handleDeleteChatGroupAvatar))
	s.mux.HandleFunc("GET /api/groups/{groupID}/sessions", s.authWrap(s.handleListGroupSessions))
	s.mux.HandleFunc("POST /api/groups/{groupID}/sessions/create", s.authWrap(s.handleCreateGroupSession))
	s.mux.HandleFunc("POST /api/groups/{groupID}/sessions", s.authWrap(s.handleSaveGroupSession))
	s.mux.HandleFunc("GET /api/groups/{groupID}/sessions/{sessionID}", s.authWrap(s.handleLoadGroupSession))
	s.mux.HandleFunc("DELETE /api/groups/{groupID}/sessions/{sessionID}", s.authWrap(s.handleDeleteGroupSession))
	s.mux.HandleFunc("PATCH /api/groups/{groupID}/sessions/{sessionID}/title", s.authWrap(s.handleUpdateGroupSessionTitle))
	s.mux.HandleFunc("PATCH /api/groups/{groupID}/sessions/{sessionID}/hook-prompt", s.authWrap(s.handleUpdateGroupSessionHookPrompt))
	s.mux.HandleFunc("PATCH /api/groups/{groupID}/sessions/{sessionID}/messages/{messageID}", s.authWrap(s.handleUpdateGroupSessionMessage))
	s.mux.HandleFunc("DELETE /api/groups/{groupID}/sessions/{sessionID}/messages/{messageID}", s.authWrap(s.handleDeleteGroupSessionMessage))
	s.mux.HandleFunc("DELETE /api/groups/{groupID}/sessions/{sessionID}/messages/{messageID}/subtree", s.authWrap(s.handleDeleteGroupSessionMessageSubtree))

	s.mux.HandleFunc("GET /api/workspaces", s.authWrap(s.handleListWorkspaces))
	s.mux.HandleFunc("POST /api/workspaces", s.authWrap(s.handleSaveWorkspace))
	s.mux.HandleFunc("POST /api/workspaces/prompt-preview", s.authWrap(s.handlePreviewWorkspacePrompt))
	s.mux.HandleFunc("GET /api/workspaces/{workspaceID}", s.authWrap(s.handleLoadWorkspace))
	s.mux.HandleFunc("DELETE /api/workspaces/{workspaceID}", s.authWrap(s.handleDeleteWorkspace))
	s.mux.HandleFunc("GET /api/workspaces/{workspaceID}/roles/{roleID}/sessions", s.authWrap(s.handleListWorkspaceSessions))
	s.mux.HandleFunc("POST /api/workspaces/{workspaceID}/roles/{roleID}/sessions/create", s.authWrap(s.handleCreateWorkspaceSession))
	s.mux.HandleFunc("POST /api/workspaces/{workspaceID}/roles/{roleID}/sessions", s.authWrap(s.handleSaveWorkspaceSession))
	s.mux.HandleFunc("GET /api/workspaces/{workspaceID}/roles/{roleID}/sessions/{sessionID}", s.authWrap(s.handleLoadWorkspaceSession))
	s.mux.HandleFunc("DELETE /api/workspaces/{workspaceID}/roles/{roleID}/sessions/{sessionID}", s.authWrap(s.handleDeleteWorkspaceSession))
	s.mux.HandleFunc("PATCH /api/workspaces/{workspaceID}/roles/{roleID}/sessions/{sessionID}/title", s.authWrap(s.handleUpdateWorkspaceSessionTitle))
	s.mux.HandleFunc("PATCH /api/workspaces/{workspaceID}/roles/{roleID}/sessions/{sessionID}/hook-prompt", s.authWrap(s.handleUpdateWorkspaceSessionHookPrompt))
	s.mux.HandleFunc("PATCH /api/workspaces/{workspaceID}/roles/{roleID}/sessions/{sessionID}/messages/{messageID}", s.authWrap(s.handleUpdateWorkspaceSessionMessage))
	s.mux.HandleFunc("DELETE /api/workspaces/{workspaceID}/roles/{roleID}/sessions/{sessionID}/messages/{messageID}", s.authWrap(s.handleDeleteWorkspaceSessionMessage))
	s.mux.HandleFunc("DELETE /api/workspaces/{workspaceID}/roles/{roleID}/sessions/{sessionID}/messages/{messageID}/subtree", s.authWrap(s.handleDeleteWorkspaceSessionMessageSubtree))

	s.mux.HandleFunc("GET /api/roles/{roleID}/sessions", s.authWrap(s.handleListSessions))
	s.mux.HandleFunc("POST /api/roles/{roleID}/sessions/create", s.authWrap(s.handleCreateSession))
	s.mux.HandleFunc("POST /api/roles/{roleID}/sessions", s.authWrap(s.handleSaveSession))
	s.mux.HandleFunc("GET /api/roles/{roleID}/sessions/{sessionID}", s.authWrap(s.handleLoadSession))
	s.mux.HandleFunc("DELETE /api/roles/{roleID}/sessions/{sessionID}", s.authWrap(s.handleDeleteSession))
	s.mux.HandleFunc("PATCH /api/roles/{roleID}/sessions/{sessionID}/title", s.authWrap(s.handleUpdateSessionTitle))
	s.mux.HandleFunc("PATCH /api/roles/{roleID}/sessions/{sessionID}/hook-prompt", s.authWrap(s.handleUpdateSessionHookPrompt))
	s.mux.HandleFunc("PATCH /api/roles/{roleID}/sessions/{sessionID}/messages/{messageID}", s.authWrap(s.handleUpdateSessionMessage))
	s.mux.HandleFunc("DELETE /api/roles/{roleID}/sessions/{sessionID}/messages/{messageID}", s.authWrap(s.handleDeleteSessionMessage))
	s.mux.HandleFunc("DELETE /api/roles/{roleID}/sessions/{sessionID}/messages/{messageID}/subtree", s.authWrap(s.handleDeleteSessionMessageSubtree))
	s.mux.HandleFunc("GET /api/sessions/favorites", s.authWrap(s.handleLoadSessionFavorites))
	s.mux.HandleFunc("PUT /api/sessions/favorites", s.authWrap(s.handleSaveSessionFavorites))
	s.mux.HandleFunc("GET /api/session-attachments/image", s.authWrap(s.handleLoadSessionAttachmentImage))

	s.mux.HandleFunc("GET /api/providers", s.authWrap(s.handleListProviders))
	s.mux.HandleFunc("GET /api/providers/model-request-config", s.authWrap(s.handleLoadModelRequestConfig))
	s.mux.HandleFunc("PUT /api/providers/model-request-config", s.authWrap(s.handleSaveModelRequestConfig))
	s.mux.HandleFunc("GET /api/model-groups", s.authWrap(s.handleLoadModelGroups))
	s.mux.HandleFunc("PUT /api/model-groups", s.authWrap(s.handleSaveModelGroups))
	s.mux.HandleFunc("POST /api/providers", s.authWrap(s.handleSaveProvider))
	s.mux.HandleFunc("GET /api/providers/{providerID}", s.authWrap(s.handleLoadProvider))
	s.mux.HandleFunc("DELETE /api/providers/{providerID}", s.authWrap(s.handleDeleteProvider))
	s.mux.HandleFunc("POST /api/providers/{providerID}/models/refresh", s.authWrap(s.handleRefreshProviderModels))

	s.mux.HandleFunc("GET /api/tools", s.authWrap(s.handleListTools))
	s.mux.HandleFunc("POST /api/tools", s.authWrap(s.handleSaveTool))
	s.mux.HandleFunc("GET /api/tools/{toolID}", s.authWrap(s.handleLoadTool))
	s.mux.HandleFunc("PUT /api/tools/{toolID}/user-config", s.authWrap(s.handleSaveToolUserSettings))

	s.mux.HandleFunc("GET /api/stickers", s.authWrap(s.handleLoadStickerLibrary))
	s.mux.HandleFunc("GET /api/stickers/image", s.authWrap(s.handleLoadStickerImage))
	s.mux.HandleFunc("POST /api/stickers/categories", s.authWrap(s.handleCreateStickerCategory))
	s.mux.HandleFunc("GET /api/stickers/categories", s.authWrap(s.handleListStickerCategories))
	s.mux.HandleFunc("GET /api/stickers/categories/{categoryName}", s.authWrap(s.handleLoadStickerCategory))
	s.mux.HandleFunc("DELETE /api/stickers/categories/{categoryName}", s.authWrap(s.handleDeleteStickerCategory))
	s.mux.HandleFunc("POST /api/stickers/items", s.authWrap(s.handleAddSticker))
	s.mux.HandleFunc("PATCH /api/stickers/items/name", s.authWrap(s.handleRenameSticker))
	s.mux.HandleFunc("DELETE /api/stickers/items", s.authWrap(s.handleDeleteSticker))
	s.mux.HandleFunc("GET /api/assist/stickers/name/config", s.authWrap(s.handleLoadStickerNamingConfig))
	s.mux.HandleFunc("PUT /api/assist/stickers/name/config", s.authWrap(s.handleSaveStickerNamingConfig))
	s.mux.HandleFunc("POST /api/assist/stickers/name", s.authWrap(s.handleGenerateStickerName))
	s.mux.HandleFunc("GET /api/assist/mermaid-fix/config", s.authWrap(s.handleLoadMermaidFixConfig))
	s.mux.HandleFunc("PUT /api/assist/mermaid-fix/config", s.authWrap(s.handleSaveMermaidFixConfig))
	s.mux.HandleFunc("POST /api/assist/mermaid-fix", s.authWrap(s.handleFixMermaidInMessage))
	s.mux.HandleFunc("GET /api/assist/chat-title/config", s.authWrap(s.handleLoadChatTitleNamingConfig))
	s.mux.HandleFunc("PUT /api/assist/chat-title/config", s.authWrap(s.handleSaveChatTitleNamingConfig))
	s.mux.HandleFunc("POST /api/assist/chat-title", s.authWrap(s.handleGenerateChatTitle))
	s.mux.HandleFunc("GET /api/assist/context-compression/config", s.authWrap(s.handleLoadContextCompressionConfig))
	s.mux.HandleFunc("PUT /api/assist/context-compression/config", s.authWrap(s.handleSaveContextCompressionConfig))
	s.mux.HandleFunc("GET /api/hook-prompts", s.authWrap(s.handleLoadHookPromptLibrary))
	s.mux.HandleFunc("PUT /api/hook-prompts", s.authWrap(s.handleSaveHookPromptLibrary))
	s.mux.HandleFunc("GET /api/placeholders", s.authWrap(s.handleLoadPlaceholderLibrary))
	s.mux.HandleFunc("PUT /api/placeholders", s.authWrap(s.handleSavePlaceholderLibrary))
	s.mux.HandleFunc("POST /api/placeholders/preview", s.authWrap(s.handlePreviewPlaceholders))
	s.mux.HandleFunc("GET /api/placeholders/problems", s.authWrap(s.handlePlaceholderProblems))
	s.mux.HandleFunc("GET /api/placeholders/dependencies/{name}", s.authWrap(s.handlePlaceholderDependencies))
	s.mux.HandleFunc("GET /api/placeholders/plugin-interfaces", s.authWrap(s.handleListAvailablePluginPlaceholderInterfaces))
	s.mux.HandleFunc("POST /api/placeholders/plugin-interfaces", s.authWrap(s.handleCreatePlaceholderFromPluginInterface))
	s.mux.HandleFunc("GET /api/system-plugins", s.authWrap(s.handleListSystemPlugins))
	s.mux.HandleFunc("GET /api/system-plugins/{pluginID}", s.authWrap(s.handleLoadSystemPlugin))
	s.mux.HandleFunc("PUT /api/system-plugins/{pluginID}/user-config", s.authWrap(s.handleSaveSystemPluginUserConfig))

	s.mux.HandleFunc("GET /ws/events", s.handleEventsWebSocket)
}
